// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/order-middleware/pkg/db/ent/orderstatebase"
	"github.com/NpoolPlatform/order-middleware/pkg/db/ent/predicate"
)

// OrderStateBaseDelete is the builder for deleting a OrderStateBase entity.
type OrderStateBaseDelete struct {
	config
	hooks    []Hook
	mutation *OrderStateBaseMutation
}

// Where appends a list predicates to the OrderStateBaseDelete builder.
func (osbd *OrderStateBaseDelete) Where(ps ...predicate.OrderStateBase) *OrderStateBaseDelete {
	osbd.mutation.Where(ps...)
	return osbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (osbd *OrderStateBaseDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(osbd.hooks) == 0 {
		affected, err = osbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OrderStateBaseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			osbd.mutation = mutation
			affected, err = osbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(osbd.hooks) - 1; i >= 0; i-- {
			if osbd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = osbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, osbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (osbd *OrderStateBaseDelete) ExecX(ctx context.Context) int {
	n, err := osbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (osbd *OrderStateBaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: orderstatebase.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: orderstatebase.FieldID,
			},
		},
	}
	if ps := osbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, osbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// OrderStateBaseDeleteOne is the builder for deleting a single OrderStateBase entity.
type OrderStateBaseDeleteOne struct {
	osbd *OrderStateBaseDelete
}

// Exec executes the deletion query.
func (osbdo *OrderStateBaseDeleteOne) Exec(ctx context.Context) error {
	n, err := osbdo.osbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderstatebase.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (osbdo *OrderStateBaseDeleteOne) ExecX(ctx context.Context) {
	osbdo.osbd.ExecX(ctx)
}
