// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/order-middleware/pkg/db/ent/paymenttransfer"
	"github.com/NpoolPlatform/order-middleware/pkg/db/ent/predicate"
)

// PaymentTransferQuery is the builder for querying PaymentTransfer entities.
type PaymentTransferQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PaymentTransfer
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaymentTransferQuery builder.
func (ptq *PaymentTransferQuery) Where(ps ...predicate.PaymentTransfer) *PaymentTransferQuery {
	ptq.predicates = append(ptq.predicates, ps...)
	return ptq
}

// Limit adds a limit step to the query.
func (ptq *PaymentTransferQuery) Limit(limit int) *PaymentTransferQuery {
	ptq.limit = &limit
	return ptq
}

// Offset adds an offset step to the query.
func (ptq *PaymentTransferQuery) Offset(offset int) *PaymentTransferQuery {
	ptq.offset = &offset
	return ptq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ptq *PaymentTransferQuery) Unique(unique bool) *PaymentTransferQuery {
	ptq.unique = &unique
	return ptq
}

// Order adds an order step to the query.
func (ptq *PaymentTransferQuery) Order(o ...OrderFunc) *PaymentTransferQuery {
	ptq.order = append(ptq.order, o...)
	return ptq
}

// First returns the first PaymentTransfer entity from the query.
// Returns a *NotFoundError when no PaymentTransfer was found.
func (ptq *PaymentTransferQuery) First(ctx context.Context) (*PaymentTransfer, error) {
	nodes, err := ptq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{paymenttransfer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ptq *PaymentTransferQuery) FirstX(ctx context.Context) *PaymentTransfer {
	node, err := ptq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaymentTransfer ID from the query.
// Returns a *NotFoundError when no PaymentTransfer ID was found.
func (ptq *PaymentTransferQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = ptq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{paymenttransfer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ptq *PaymentTransferQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := ptq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaymentTransfer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PaymentTransfer entity is found.
// Returns a *NotFoundError when no PaymentTransfer entities are found.
func (ptq *PaymentTransferQuery) Only(ctx context.Context) (*PaymentTransfer, error) {
	nodes, err := ptq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{paymenttransfer.Label}
	default:
		return nil, &NotSingularError{paymenttransfer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ptq *PaymentTransferQuery) OnlyX(ctx context.Context) *PaymentTransfer {
	node, err := ptq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaymentTransfer ID in the query.
// Returns a *NotSingularError when more than one PaymentTransfer ID is found.
// Returns a *NotFoundError when no entities are found.
func (ptq *PaymentTransferQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = ptq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{paymenttransfer.Label}
	default:
		err = &NotSingularError{paymenttransfer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ptq *PaymentTransferQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := ptq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaymentTransfers.
func (ptq *PaymentTransferQuery) All(ctx context.Context) ([]*PaymentTransfer, error) {
	if err := ptq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ptq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ptq *PaymentTransferQuery) AllX(ctx context.Context) []*PaymentTransfer {
	nodes, err := ptq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaymentTransfer IDs.
func (ptq *PaymentTransferQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := ptq.Select(paymenttransfer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ptq *PaymentTransferQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := ptq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ptq *PaymentTransferQuery) Count(ctx context.Context) (int, error) {
	if err := ptq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ptq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ptq *PaymentTransferQuery) CountX(ctx context.Context) int {
	count, err := ptq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ptq *PaymentTransferQuery) Exist(ctx context.Context) (bool, error) {
	if err := ptq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ptq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ptq *PaymentTransferQuery) ExistX(ctx context.Context) bool {
	exist, err := ptq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaymentTransferQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ptq *PaymentTransferQuery) Clone() *PaymentTransferQuery {
	if ptq == nil {
		return nil
	}
	return &PaymentTransferQuery{
		config:     ptq.config,
		limit:      ptq.limit,
		offset:     ptq.offset,
		order:      append([]OrderFunc{}, ptq.order...),
		predicates: append([]predicate.PaymentTransfer{}, ptq.predicates...),
		// clone intermediate query.
		sql:    ptq.sql.Clone(),
		path:   ptq.path,
		unique: ptq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PaymentTransfer.Query().
//		GroupBy(paymenttransfer.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ptq *PaymentTransferQuery) GroupBy(field string, fields ...string) *PaymentTransferGroupBy {
	grbuild := &PaymentTransferGroupBy{config: ptq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ptq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ptq.sqlQuery(ctx), nil
	}
	grbuild.label = paymenttransfer.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.PaymentTransfer.Query().
//		Select(paymenttransfer.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (ptq *PaymentTransferQuery) Select(fields ...string) *PaymentTransferSelect {
	ptq.fields = append(ptq.fields, fields...)
	selbuild := &PaymentTransferSelect{PaymentTransferQuery: ptq}
	selbuild.label = paymenttransfer.Label
	selbuild.flds, selbuild.scan = &ptq.fields, selbuild.Scan
	return selbuild
}

func (ptq *PaymentTransferQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ptq.fields {
		if !paymenttransfer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ptq.path != nil {
		prev, err := ptq.path(ctx)
		if err != nil {
			return err
		}
		ptq.sql = prev
	}
	if paymenttransfer.Policy == nil {
		return errors.New("ent: uninitialized paymenttransfer.Policy (forgotten import ent/runtime?)")
	}
	if err := paymenttransfer.Policy.EvalQuery(ctx, ptq); err != nil {
		return err
	}
	return nil
}

func (ptq *PaymentTransferQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PaymentTransfer, error) {
	var (
		nodes = []*PaymentTransfer{}
		_spec = ptq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*PaymentTransfer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &PaymentTransfer{config: ptq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ptq.modifiers) > 0 {
		_spec.Modifiers = ptq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ptq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ptq *PaymentTransferQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ptq.querySpec()
	if len(ptq.modifiers) > 0 {
		_spec.Modifiers = ptq.modifiers
	}
	_spec.Node.Columns = ptq.fields
	if len(ptq.fields) > 0 {
		_spec.Unique = ptq.unique != nil && *ptq.unique
	}
	return sqlgraph.CountNodes(ctx, ptq.driver, _spec)
}

func (ptq *PaymentTransferQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ptq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ptq *PaymentTransferQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   paymenttransfer.Table,
			Columns: paymenttransfer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: paymenttransfer.FieldID,
			},
		},
		From:   ptq.sql,
		Unique: true,
	}
	if unique := ptq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ptq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymenttransfer.FieldID)
		for i := range fields {
			if fields[i] != paymenttransfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ptq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ptq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ptq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ptq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ptq *PaymentTransferQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ptq.driver.Dialect())
	t1 := builder.Table(paymenttransfer.Table)
	columns := ptq.fields
	if len(columns) == 0 {
		columns = paymenttransfer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ptq.sql != nil {
		selector = ptq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ptq.unique != nil && *ptq.unique {
		selector.Distinct()
	}
	for _, m := range ptq.modifiers {
		m(selector)
	}
	for _, p := range ptq.predicates {
		p(selector)
	}
	for _, p := range ptq.order {
		p(selector)
	}
	if offset := ptq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ptq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (ptq *PaymentTransferQuery) ForUpdate(opts ...sql.LockOption) *PaymentTransferQuery {
	if ptq.driver.Dialect() == dialect.Postgres {
		ptq.Unique(false)
	}
	ptq.modifiers = append(ptq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return ptq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (ptq *PaymentTransferQuery) ForShare(opts ...sql.LockOption) *PaymentTransferQuery {
	if ptq.driver.Dialect() == dialect.Postgres {
		ptq.Unique(false)
	}
	ptq.modifiers = append(ptq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return ptq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ptq *PaymentTransferQuery) Modify(modifiers ...func(s *sql.Selector)) *PaymentTransferSelect {
	ptq.modifiers = append(ptq.modifiers, modifiers...)
	return ptq.Select()
}

// PaymentTransferGroupBy is the group-by builder for PaymentTransfer entities.
type PaymentTransferGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ptgb *PaymentTransferGroupBy) Aggregate(fns ...AggregateFunc) *PaymentTransferGroupBy {
	ptgb.fns = append(ptgb.fns, fns...)
	return ptgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ptgb *PaymentTransferGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ptgb.path(ctx)
	if err != nil {
		return err
	}
	ptgb.sql = query
	return ptgb.sqlScan(ctx, v)
}

func (ptgb *PaymentTransferGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ptgb.fields {
		if !paymenttransfer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ptgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ptgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ptgb *PaymentTransferGroupBy) sqlQuery() *sql.Selector {
	selector := ptgb.sql.Select()
	aggregation := make([]string, 0, len(ptgb.fns))
	for _, fn := range ptgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ptgb.fields)+len(ptgb.fns))
		for _, f := range ptgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ptgb.fields...)...)
}

// PaymentTransferSelect is the builder for selecting fields of PaymentTransfer entities.
type PaymentTransferSelect struct {
	*PaymentTransferQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pts *PaymentTransferSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pts.prepareQuery(ctx); err != nil {
		return err
	}
	pts.sql = pts.PaymentTransferQuery.sqlQuery(ctx)
	return pts.sqlScan(ctx, v)
}

func (pts *PaymentTransferSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pts.sql.Query()
	if err := pts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pts *PaymentTransferSelect) Modify(modifiers ...func(s *sql.Selector)) *PaymentTransferSelect {
	pts.modifiers = append(pts.modifiers, modifiers...)
	return pts
}
