// Code generated by ent, DO NOT EDIT.

package orderstate

import (
	"entgo.io/ent"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the orderstate type in the database.
	Label = "order_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldOrderState holds the string denoting the order_state field in the database.
	FieldOrderState = "order_state"
	// FieldEndAt holds the string denoting the end_at field in the database.
	FieldEndAt = "end_at"
	// FieldLastBenefitAt holds the string denoting the last_benefit_at field in the database.
	FieldLastBenefitAt = "last_benefit_at"
	// FieldBenefitState holds the string denoting the benefit_state field in the database.
	FieldBenefitState = "benefit_state"
	// FieldUserSetPaid holds the string denoting the user_set_paid field in the database.
	FieldUserSetPaid = "user_set_paid"
	// FieldUserSetCancelled holds the string denoting the user_set_cancelled field in the database.
	FieldUserSetCancelled = "user_set_cancelled"
	// FieldPaymentTransactionID holds the string denoting the payment_transaction_id field in the database.
	FieldPaymentTransactionID = "payment_transaction_id"
	// FieldPaymentFinishAmount holds the string denoting the payment_finish_amount field in the database.
	FieldPaymentFinishAmount = "payment_finish_amount"
	// FieldPaymentState holds the string denoting the payment_state field in the database.
	FieldPaymentState = "payment_state"
	// Table holds the table name of the orderstate in the database.
	Table = "order_states"
)

// Columns holds all SQL columns for orderstate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldOrderID,
	FieldOrderState,
	FieldEndAt,
	FieldLastBenefitAt,
	FieldBenefitState,
	FieldUserSetPaid,
	FieldUserSetCancelled,
	FieldPaymentTransactionID,
	FieldPaymentFinishAmount,
	FieldPaymentState,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/order-middleware/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultOrderState holds the default value on creation for the "order_state" field.
	DefaultOrderState string
	// DefaultEndAt holds the default value on creation for the "end_at" field.
	DefaultEndAt uint32
	// DefaultLastBenefitAt holds the default value on creation for the "last_benefit_at" field.
	DefaultLastBenefitAt uint32
	// DefaultBenefitState holds the default value on creation for the "benefit_state" field.
	DefaultBenefitState string
	// DefaultUserSetPaid holds the default value on creation for the "user_set_paid" field.
	DefaultUserSetPaid bool
	// DefaultUserSetCancelled holds the default value on creation for the "user_set_cancelled" field.
	DefaultUserSetCancelled bool
	// DefaultPaymentTransactionID holds the default value on creation for the "payment_transaction_id" field.
	DefaultPaymentTransactionID string
	// DefaultPaymentFinishAmount holds the default value on creation for the "payment_finish_amount" field.
	DefaultPaymentFinishAmount decimal.Decimal
	// DefaultPaymentState holds the default value on creation for the "payment_state" field.
	DefaultPaymentState string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
